localeurlcustom/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from localeurlcustom.views import change_locale

urlpatterns = patterns('',
	url(r'^change/', change_locale, name='localeurl_change_locale'),
)

pycon/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url('program_export/', views.program_export, name='program_export'),
)

symposion/cms/urls.py
from django.conf.urls.defaults import url, patterns

PAGE_RE = r"(([\w-]{1,})(/[\w-]{1,})*)/"

urlpatterns = patterns("symposion.cms.views",
    url(r"^files/$", "file_index", name="file_index"),
    url(r"^files/create/$", "file_create", name="file_create"),
    url(r"^files/(\d+)/([^/]+)$", "file_download", name="file_download"),
    url(r"^files/(\d+)/delete/$", "file_delete", name="file_delete"),
    url(r"^(?P<path>%s)_edit/$" % PAGE_RE, "page_edit", name="cms_page_edit"),
    url(r"^(?P<path>%s)$" % PAGE_RE, "page", name="cms_page"),
)

symposion/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static

from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

admin.autodiscover()

import symposion.views

# from pinax.apps.account.openid_consumer import PinaxConsumer


URL_PREFIX = settings.CONFERENCE_URL_PREFIXES[settings.CONFERENCE_ID]


urlpatterns = patterns("",
    url(r"^$", RedirectView.as_view(url="/%s/" % URL_PREFIX)),
    url(r"^%s/" % URL_PREFIX, include(patterns("",
        url(r"^$", TemplateView.as_view(template_name="homepage.html"),
            name="home"),
        url(r"^admin/", include(admin.site.urls)),
        url(r"^account/signup/$", symposion.views.SignupView.as_view(), name="account_signup"),
        url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
        url(r"^account/social/", include("social_auth.urls")),
        url(r"^account/associations/", include("symposion.social_auth.urls")),
        url(r"^account/", include("account.urls")),
        url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
        url(r"^blog/", include("biblion.urls")),
        url(r"^force500/", lambda request: xxx),

        url(r"^registration/", include("pycon.registration.urls")),

        url(r"^venue/$", TemplateView.as_view(template_name="venue/detail.html"), name="venue_detail"),
        url(r"^venue/traveling/", TemplateView.as_view(template_name="venue/traveling.html"), name="traveling"),
        url(r"^venue/directions/", TemplateView.as_view(template_name="venue/directions.html"), name="directions"),
        url(r"^venue/getting-around/", TemplateView.as_view(template_name="venue/getting_around.html"), name="getting_around"),
        url(r"^venue/weather/", TemplateView.as_view(template_name="venue/weather.html"), name="weather"),
        url(r"^venue/explore/", TemplateView.as_view(template_name="venue/explore.html"), name="explore"),
        url(r"^venue/restaurants/", TemplateView.as_view(template_name="venue/restaurants.html"), name="restaurants"),
        url(r"^venue/bars/", TemplateView.as_view(template_name="venue/bars.html"), name="bars"),
        url(r"^venue/shopping/", TemplateView.as_view(template_name="venue/shopping.html"), name="shopping"),
        url(r"^venue/share-room/", TemplateView.as_view(template_name="venue/share_room.html"), name="share_room"),
        url(r"^venue/hotels/", TemplateView.as_view(template_name="venue/hotels.html"), name="hotels"),

        url(r"^finaid/", include("pycon.finaid.urls")),
        url(r"^pycon_api/", include("pycon.pycon_api.urls")),
        url(r"^schedule/", include("pycon.schedule.urls")),
        url(r"^profile/", include("pycon.profile.urls")),
        url(r"^tutorials/", include("pycon.tutorials.urls")),

        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposals/", include("symposion.proposals.urls")),
        url(r"^reviews/", include("symposion.reviews.urls")),
        url(r"^teams/", include("symposion.teams.urls")),
        url(r"^schedule/", include("symposion.schedule.urls")),
        url(r"^conference/", include("symposion.conference.urls")),

        url(r"^sponsors/", include("pycon.sponsorship.urls")),

        url(r"^boxes/", include("symposion.boxes.urls")),
        url(r"^sitemap/", TemplateView.as_view(template_name="static/sitemap.html"), name="sitemap"),
        url(r'^selectable/', include('selectable.urls')),
        url(r"^change_language/", symposion.views.change_language, name="change_language"),
        url(r"^", include("pycon.urls")),

        # This should be last, because it will create a new CMS page for
        # any unrecognized URL.
        url(r"^", include("symposion.cms.urls")),
    )))
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pycon/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _

from symposion.proposals.models import ProposalBase


class PyConProposalCategory(models.Model):

    name = models.CharField(max_length=100)
    slug = models.SlugField()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "PyCon proposal category"
        verbose_name_plural = "PyCon proposal categories"


class ThunderdomeGroup(models.Model):
    """A set of talk proposals, grouped together for consideration within
    thunderdome.
    """
    label = models.CharField(max_length=250)
    code = models.CharField(max_length=20, unique=True)
    decided = models.BooleanField(default=False, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    @property
    def as_dict(self):
        return {
            'code': self.code,
            'decided': self.decided,
            'label': self.label,
            'talks': [i.as_dict() for i in self.talks.order_by('id')],
        }


class PyConProposal(ProposalBase):

    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3

    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, _(u"Novice")),
        (AUDIENCE_LEVEL_INTERMEDIATE, _(u"Intermediate")),
        (AUDIENCE_LEVEL_EXPERIENCED, _(u"Experienced")),
    ]

    STATUS_UNREVIEWED = 1
    STATUS_KITTENDOME = 2
    STATUS_THUNDERDOME = 3
    STATUS_ACCEPTED = 4
    STATUS_DAMAGED = 5
    STATUS_REJECTED = 6

    STATUS_OPTIONS = [
        (STATUS_UNREVIEWED, 'Not Yet Reviewed'),
        (STATUS_KITTENDOME, 'In Kittendome'),
        (STATUS_THUNDERDOME, 'In Thunderdome'),
        (STATUS_ACCEPTED, 'Accepted'),
        (STATUS_DAMAGED, 'Damaged'),
        (STATUS_REJECTED, 'Rejected'),
    ]

    REJECTION_POSTER = 1
    REJECTION_LIGHTNING = 2
    REJECTION_MOVED = 3
    REJECTION_DUPLICATE = 4
    REJECTION_ADMIN = 5
    REJECTION_BAD = 6

    REJECTION_OPTIONS = [
        (REJECTION_POSTER, 'Suggest re-submission as poster.'),
        (REJECTION_LIGHTNING, 'Suggest lightning talk.'),
        (REJECTION_MOVED, 'Re-submitted under appropriate category.'),
        (REJECTION_DUPLICATE, 'Duplicate'),
        (REJECTION_ADMIN, 'Administrative Action (Other)'),
        (REJECTION_BAD, "No really: rejected. It's just plain bad."),
    ]

    category = models.ForeignKey(PyConProposalCategory, verbose_name=_("Category"))
    audience_level = models.IntegerField(
        choices=AUDIENCE_LEVELS,
        help_text=_(u'Level of audience expertise assumed in Python.'),
        verbose_name=_(u'Python level'))
    overall_status = models.IntegerField(
        choices=STATUS_OPTIONS,
        default=STATUS_UNREVIEWED,
        help_text=_(u'The status of the proposal.'))
    damaged_score = models.IntegerField(
        blank=True,
        null=True,
        help_text=_(u"Numerical indicator of the amount of interest in a talk set to 'damaged' status."))
    rejection_status = models.IntegerField(
        blank=True,
        null=True,
        choices=REJECTION_OPTIONS,
        help_text=_(u'The reason the proposal was rejected.'))
    recording_release = models.BooleanField(
        _("Recording Release"),
        default=True,
        help_text=_(u"By submitting your talk proposal, you agree to give permission to the PyCon JP Management Team to record, edit, and release audio and/or video of your presentation. If you do not agree to this, please uncheck this box.")
    )

    additional_requirements = models.TextField(
        _(u"Additional requirements"),
        blank=True,
        help_text=_(u"Please let us know if you have any specific needs (A/V requirements, multiple microphones, a table, etc).  Note for example that 'audio out' is not provided for your computer unless you tell us in advance.")
    )

    class Meta:
        abstract = True


class PyConTalkProposal(PyConProposal):

    DURATION_CHOICES = [
        (0, _(u"No preference")),
        (1, _(u"I prefer a 30 minute slot")),
        (2, _(u"I prefer a 45 minute slot")),
    ]

    duration = models.IntegerField(choices=DURATION_CHOICES, verbose_name=_("Duration"))

    outline = models.TextField(
        verbose_name = _(u"Outline"),
        help_text = _("Please write outline of your presentation. "
                    "This is not published. it is referenced by reviview.")
    )
    audience = models.CharField(
        max_length=150,
        verbose_name=_("Audience"),
        help_text=_(u'Who is the intended audience for your talk? (Be '
                    u'specific; "Python programmers" is not a good answer '
                    u'to this question.)'),
    )
    perceived_value = models.TextField(
        _(u"Objectives"),
        max_length=400,
        help_text=_(u"What will attendees get out of your talk? When they "
                    u"leave the room, what will they know that they didn't "
                    u"know before?"),
    )

    thunderdome_group = models.ForeignKey(ThunderdomeGroup,
        blank=True,
        default=None,
        null=True,
        related_name=u'talks',
    )

    class Meta:
        verbose_name = "PyCon talk proposal"

    def as_dict(self, details=False):
        answer = super(PyConTalkProposal, self).as_dict(details=details)
        if details:
            code = None
            if self.thunderdome_group:
                code = self.thunderdome_group.code
            answer['thunderdome_group'] = code
        return answer


class PyConLightningTalkProposal(PyConProposal):

    class Meta:
        verbose_name = "PyCon lightning talk proposal"


class PyConTutorialProposal(PyConProposal):
    DOMAIN_LEVEL_NOVICE = 1
    DOMAIN_LEVEL_EXPERIENCED = 2
    DOMAIN_LEVEL_INTERMEDIATE = 3

    DOMAIN_LEVELS = [
        (DOMAIN_LEVEL_NOVICE, _(u"Novice")),
        (DOMAIN_LEVEL_INTERMEDIATE, _(u"Intermediate")),
        (DOMAIN_LEVEL_EXPERIENCED, _(u"Experienced")),
    ]

    domain_level = models.IntegerField(
        choices=DOMAIN_LEVELS,
        help_text=_(u'Level of audience expertise assumed in the '
                    u'presentation\'s domain.'))

    outline = models.TextField(
        _(u"Outline")
    )
    more_info = models.TextField(
        _(u"More info"),
        help_text=_(u"More info. Will be made public if your talk is accepted.")
    )
    audience = models.CharField(
        max_length=150,
        help_text=_(u'Who is the intended audience for your talk? (Be '
                    u'specific; "Python programmers" is not a good answer '
                    u'to this question.)'),
    )
    perceived_value = models.TextField(
        _(u"Objectives"),
        max_length=500,
        help_text=_(u"What will attendees get out of your talk? When they "
                    u"leave the room, what will they know that they didn't "
                    u"know before?"),
    )
    handout = models.FileField(
        _(u"Student Handout"),
        blank=True,
        null=True,
        help_text=_(u'Upload a resource to be distributed to students  '
                    u'attending the tutorial session.'),
        upload_to="tutorial_handouts"
    )

    registrants = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        help_text=_(u'CTE registered participants for this tutorial.'),
        )

    cte_tutorial_id = models.CharField(
        max_length=150,
        help_text=_(u'CTE Tutorial Identifier. This is typically auto-populated'
                    u' from a management command.'),
        blank=True,
        default="")

    max_attendees = models.IntegerField(
        blank=True,
        null=True,
        help_text=_(u'Maximum number of attendees, per CTE data'))


    class Meta:
        verbose_name = "PyCon tutorial proposal"


class PyConPosterProposal(PyConProposal):
    class Meta:
        verbose_name = "PyCon Poster proposal"


class PyConSponsorTutorialProposal(ProposalBase):
    class Meta:
        verbose_name = "PyCon Sponsor Tutorial proposal"

    def __unicode__(self):
        return self.title


class PyConOpenSpaceProposal(PyConProposal):
    class Meta:
        verbose_name = "PyCon Open Space proposal"

pycon/schedule/models.py
from datetime import datetime

from django.db import models

from django.contrib.auth.models import User

from symposion.schedule.models import Day, Slot


class Session(models.Model):

    day = models.ForeignKey(Day, related_name="sessions")
    slots = models.ManyToManyField(Slot, related_name="sessions")

    def sorted_slots(self):
        return self.slots.order_by("start")

    def start(self):
        slots = self.sorted_slots()
        if slots:
            return list(slots)[0].start
        else:
            return None

    def end(self):
        slots = self.sorted_slots()
        if slots:
            return list(slots)[-1].end
        else:
            return None

    def __unicode__(self):
        start = self.start()
        end = self.end()
        if start and end:
            return u"%s: %s - %s" % (
                self.day.date.strftime("%a"),
                start.strftime("%X"),
                end.strftime("%X")
            )
        return u""


class SessionRole(models.Model):

    SESSION_ROLE_CHAIR = 1
    SESSION_ROLE_RUNNER = 2

    SESSION_ROLE_TYPES = [
        (SESSION_ROLE_CHAIR, "Session Chair"),
        (SESSION_ROLE_RUNNER, "Session Runner"),
    ]

    session = models.ForeignKey(Session)
    user = models.ForeignKey(User)
    role = models.IntegerField(choices=SESSION_ROLE_TYPES)
    status = models.NullBooleanField()

    submitted = models.DateTimeField(default=datetime.now)

    class Meta:
        unique_together = [("session", "user", "role")]

    def __unicode__(self):
        return u"%s %s: %s" % (self.user, self.session,
                               self.SESSION_ROLE_TYPES[self.role-1][1])

symposion/boxes/models.py
from django.db import models

from django.contrib.auth.models import User

import reversion


class Box(models.Model):

    label = models.CharField(max_length=100, db_index=True)
    content = models.TextField(blank=True)

    created_by = models.ForeignKey(User, related_name="boxes")
    last_updated_by = models.ForeignKey(User, related_name="updated_boxes")

    def __unicode__(self):
        return self.label

    class Meta:
        verbose_name_plural = "boxes"


reversion.register(Box)

symposion/boxes/forms.py
from django import forms

from markedit.widgets import MarkEdit

from symposion.boxes.models import Box


class BoxForm(forms.ModelForm):

    class Meta:
        model = Box
        fields = ["content"]
        widgets = {
            "content": MarkEdit(),
        }

symposion/cms/forms.py
from django import forms

from markedit.widgets import MarkEdit

from .models import Page


class PageForm(forms.ModelForm):

    class Meta:
        model = Page
        fields = ["title", "body", "body_fr", "path"]
        widgets = {
            "path": forms.HiddenInput(),
            "body": MarkEdit(),
            "body_fr": MarkEdit(),
        }


class FileUploadForm(forms.Form):

    file = forms.FileField()

symposion/boxes/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.views.decorators.http import require_POST

from symposion.boxes.authorization import load_can_edit
from symposion.boxes.forms import BoxForm
from symposion.boxes.models import Box


# @@@ problem with this is that the box_edit.html and box_create.html won't have domain objects in context
def get_auth_vars(request):
    auth_vars = {}
    if request.method == "POST":
        keys = [k for k in request.POST.keys() if k.startswith("boxes_auth_")]
        for key in keys:
            auth_vars[key.replace("boxes_auth_", "")] = request.POST.get(key)
        auth_vars["user"] = request.user
    return auth_vars


@require_POST
def box_edit(request, label):
    
    if not load_can_edit()(request, **get_auth_vars(request)):
        return HttpResponseForbidden()
    
    next = request.GET.get("next")
    
    try:
        box = Box.objects.get(label=label)
    except Box.DoesNotExist:
        box = None
    
    form = BoxForm(request.POST, instance=box, prefix=label)

    if form.is_valid():
        if box is None:
            box = form.save(commit=False)
            box.label = label
            box.created_by = request.user
            box.last_updated_by = request.user
            box.save()
        else:
            form.save()
        return redirect(next)

symposion/templates/schedule/_edit_grid.html
<table class="calendar table table-bordered">
    <thead>
        <tr>
            <th class="time">&nbsp;</th>
            {% for room in timetable.rooms %}
                <th>{{ room.name }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for row in timetable %}
            <tr>
                <td class="time">{{ row.time|date:"h:iA" }}</td>
                {% for slot in row.slots %}
                    <td class="slot slot-{{ slot.kind.label }}" colspan="{{ slot.colspan }}" rowspan="{{ slot.rowspan }}">
                        {% if slot.kind.label == "talk" or slot.kind.label == "tutorial" or slot.kind.label == "sponsor-tutorial" or slot.kind.label == "plenary" %}
                            {% if not slot.content %}
                                <a class="btn btn-mini edit-slot" data-action="{% url 'schedule_slot_edit'  schedule.section.slug slot.pk %}" href="#">+</a>
                            {% else %}
                                <span class="title"><a class="edit-slot" data-action="{% url 'schedule_slot_edit'  schedule.section.slug slot.pk %}" href="#">{{ slot.content.title }}</a></span>
                                <span class="speaker">{{ slot.content.speaker }}</span>
                            {% endif %}
                        {% else %}
                            {% if slot.content_override.raw %}
                                {{ slot.content_override.rendered|safe }}
                            {% else %}
                                {{ slot.kind.label }}
                            {% endif %}
                            &mdash; <a class="edit-slot" data-action="{% url 'schedule_slot_edit'  schedule.section.slug slot.pk %}" href="#">edit</a>
                        {% endif %}
                    </td>
                {% endfor %}
                {% if forloop.last %}
                    <td colspan="{{ timetable.rooms|length }}"></td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>

symposion/templates/schedule/_grid.html
<table class="calendar table table-bordered">
    <thead>
        <tr>
            <th class="time">&nbsp;</th>
            {% for room in timetable.rooms %}
                <th>{{ room.name }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for row in timetable %}
            <tr>
                <td class="time">{{ row.time|date:"h:iA" }}</td>
                {% for slot in row.slots %}
                    <td class="slot slot-{{ slot.kind.label }}" colspan="{{ slot.colspan }}" rowspan="{{ slot.rowspan }}">
                        {% if slot.kind.label == "talk" or slot.kind.label == "tutorial" or slot.kind.label == "sponsor-tutorial" or slot.kind.label == "plenary" %}
                            {% if not slot.content %}
                            {% else %}
                                <span class="title">
                                    <a href="{% url 'schedule_presentation_detail'  slot.content.pk %}" title="{{ slot.content.description|striptags|cut:"\"" }}">{{ slot.content.title }}</a>
                                </span>
                                <span class="speaker">
                                    {{ slot.content.speakers|join:", " }}
                                </span>
                                <div class="badges">
                                    {% for session in slot.sessions.all %}
                                        <a href="{% url 'schedule_session_detail' session.id %}" class="btn btn-mini" style="margin-right: 10px" title="Session Information">S</a>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        {% else %}
                            {% if slot.content_override.raw %}
                                {{ slot.content_override.rendered|safe }}
                            {% else %}
                                {{ slot.kind.label }}
                            {% endif %}
                        {% endif %}
                    </td>
                {% endfor %}
                {% if forloop.last %}
                    <td colspan="{{ timetable.rooms|length }}"></td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>

symposion/templates/schedule/_slot_edit.html
{% load i18n bootstrap_tags %}
<form id="slotEditForm" class="modal-form" method="POST" action="{% url 'schedule_slot_edit' slug slot.pk %}">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3>{% trans "Edit Slot" %}</h3>
    </div>
    <div class="modal-body" style="height:350px">
        {% csrf_token %}
        {{ form|as_bootstrap }}
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    </div>
</form>

symposion/templates/schedule/presentation_detail.html
{% extends "site_base.html" %}

{% load i18n %}
{% load sitetree %}

{% block head_title %}{% trans "Presentation: " %}{{ presentation.title }}{% endblock %}

{% block breadcrumbs %}{% sitetree_breadcrumbs from "main" %}{% endblock %}

{% block body %}
    {% if presentation.slot %}
        <h4>
            {{ presentation.slot.day.date|date:"l" }}
            {{ presentation.slot.start}}&ndash;{{ presentation.slot.end }}
        </h4>
    {% endif %}
    <h2>{{ presentation.title }}</h2>

    <h4>
        {% for speaker in presentation.speakers %}
            <a href="{% url 'speaker_profile' speaker.pk %}">{{ speaker }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
    </h4>

    {% if presentation.proposal.category  %}
        <dl class="dl-horizontal">
            <dt>{% trans "Audience level:" %}</dt>
            <dd style="margin-bottom: 0;">{{ presentation.proposal.get_audience_level_display }}</dd>
            <dt>{% trans "Category:" %}</dt>
            <dd>{{ presentation.proposal.category }}</dd>
        </dl>
    {% endif %}

    <h3>{% trans "Description" %}</h3>

    <div class="description">{{ presentation.description }}</div>

    <h3>{% trans "Abstract" %}</h3>

    <div class="abstract">{{ presentation.abstract|safe }}</div>
{% endblock %}

symposion/templates/schedule/schedule_conference.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap_tags %}
{% load boxes_tags %}
{% load cache %}

{% block head_title %}{% trans "Conference Schedule" %}{% endblock %}

{% block body_class %}full{% endblock %}

{% block right %}
{% endblock %}

{% block body_outer %}
    <div class="row">
        <div class="span12">
            <div class="page-head">
                <h1>{% trans "Conference Schedule" %}</h1>
                {% block breadcrumbs %}{% endblock %}
            </div>
        </div>
        <div class="span12">
            {% box "schedule_top" %}

            {% for section in sections %}
                {% cache 600 "schedule-table" section.schedule.section %}
                    {% for timetable in section.days %}
                        <h3>{{ timetable.day.date }}</h3>
                        {% include "schedule/_grid.html" %}
                    {% endfor %}
                {% endcache %}
            {% endfor %}

            {% box "schedule_bottom" %}
        </div>
    </div>
{% endblock %}

symposion/templates/schedule/schedule_detail.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap_tags %}
{% load boxes_tags %}
{% load cache %}
{% load sitetree %}

{% block head_title %}{% trans "Conference Schedule" %}{% endblock %}

{% block body_class %}full{% endblock %}

{% block right %}
{% endblock %}

{% block body_outer %}
    <div class="row">
        <div class="span12">
            <div class="page-head">
                <h1>{% blocktrans %}{{ schedule.section }} Schedule{% endblocktrans %}</h1>
                {% block breadcrumbs %}{% sitetree_breadcrumbs from "main" %}{% endblock %}
            </div>
        </div>
        <div class="span12">
            {% box "schedule_top_"|add:schedule.section.name|slugify %}
            
            {% cache 600 "schedule-table" schedule.section %}
                {% for timetable in days %}
                    <h3>{{ timetable.day.date }}</h3>
                    {% include "schedule/_grid.html" %}
                {% endfor %}
            {% endcache %}
            
            {% box "schedule_bottom_"|add:schedule.section.name|slugify %}
        </div>
    </div>
{% endblock %}

symposion/templates/schedule/schedule_edit.html
{% extends "site_base.html" %}

{% load compress %}
{% load i18n %}
{% load bootstrap_tags %}

{% block head_title %}{% trans "Conference Schedule Edit" %}{% endblock %}

{% block body_class %}full{% endblock %}

{% block right %}
{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="{{ STATIC_URL }}chosen/chosen.css" />
{% endblock %}

{% block body_outer %}
    <div class="row">
        <div class="span12">
            <h1>{% trans "Schedule Edit" %}</h1>

            {% for timetable in days %}
                <h2>{{ timetable.day.date }}</h2>
                {% include "schedule/_edit_grid.html" %}
            {% endfor %}
        </div>

        <div class="modal fade hide in" id="slotEditModal"></div>
    </div>
{% endblock %}

{% block extra_script %}
  {% compress js %}
    <script src="{{ STATIC_URL }}chosen/chosen.jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function() {
            $("a.edit-slot").click(function(e) {
                $("#slotEditModal").load($(this).data("action"), function() {
                    $("#id_presentation").chosen();
                    $("#slotEditModal").modal("show");
                });
                e.preventDefault();
            });
        });
    </script>
  {% endcompress %}
{% endblock %}

symposion/templates/schedule/session_list.html
{% extends "site_base.html" %}
{% load account_tags %}
{% load i18n %}

{% block body %}
    <h1>{% trans "Sessions" %}</h1>

    <ul class="unstyled">
        {% for session in sessions %}
            {% if session.sorted_slots %}
                <li>
                    <a href="{% url 'schedule_session_detail' session.pk %}">{% blocktrans %}Session #{% endblocktrans %}{{ {{ forloop.counter }} }}</a>
                    <div class="well">
                        <ul class="unstyled">
                            {% for role in session.sessionrole_set.all %}
                                <li>
                                    <b>{{ role.get_role_display }}</b>: {{ role.user.profile.display_name }}
                                </li>
                            {% empty %}
                                <li>{% trans "No volunteers signed up" %}</li>
                            {% endfor %}
                        </ul>
                        <h4>{% trans "Slots" %}</h4>
                        <table class="table">
                            {% for slot in session.sorted_slots %}
                                <tr>
                                    <td>{{ slot }}</td>
                                    <td>
                                        {% if slot.content %}<a href="{% url 'schedule_presentation_detail' slot.content.pk %}">{{ slot.content }}</a>{% endif %}
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>{% trans "No slots in session." %}</tr>
                            {% endfor %}
                        </table>
                    </div>
                </li>
            {% endif %}
        {% empty %}
            <li>{% trans "No sessions defined." %}</li>
        {% endfor %}
    </ul>

{% endblock %}