localeurlcustom/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from localeurlcustom.views import change_locale

urlpatterns = patterns('',
	url(r'^change/', change_locale, name='localeurl_change_locale'),
)

pycon/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url('program_export/', views.program_export, name='program_export'),
)

symposion/cms/urls.py
from django.conf.urls.defaults import url, patterns

PAGE_RE = r"(([\w-]{1,})(/[\w-]{1,})*)/"

urlpatterns = patterns("symposion.cms.views",
    url(r"^files/$", "file_index", name="file_index"),
    url(r"^files/create/$", "file_create", name="file_create"),
    url(r"^files/(\d+)/([^/]+)$", "file_download", name="file_download"),
    url(r"^files/(\d+)/delete/$", "file_delete", name="file_delete"),
    url(r"^(?P<path>%s)_edit/$" % PAGE_RE, "page_edit", name="cms_page_edit"),
    url(r"^(?P<path>%s)$" % PAGE_RE, "page", name="cms_page"),
)

symposion/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static

from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

admin.autodiscover()

import symposion.views

# from pinax.apps.account.openid_consumer import PinaxConsumer


URL_PREFIX = settings.CONFERENCE_URL_PREFIXES[settings.CONFERENCE_ID]


urlpatterns = patterns("",
    url(r"^$", RedirectView.as_view(url="/%s/" % URL_PREFIX)),
    url(r"^%s/" % URL_PREFIX, include(patterns("",
        url(r"^$", TemplateView.as_view(template_name="homepage.html"),
            name="home"),
        url(r"^admin/", include(admin.site.urls)),
        url(r"^account/signup/$", symposion.views.SignupView.as_view(), name="account_signup"),
        url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
        url(r"^account/social/", include("social_auth.urls")),
        url(r"^account/associations/", include("symposion.social_auth.urls")),
        url(r"^account/", include("account.urls")),
        url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
        url(r"^blog/", include("biblion.urls")),
        url(r"^force500/", lambda request: xxx),

        url(r"^registration/", include("pycon.registration.urls")),

        url(r"^venue/$", TemplateView.as_view(template_name="venue/detail.html"), name="venue_detail"),
        url(r"^venue/traveling/", TemplateView.as_view(template_name="venue/traveling.html"), name="traveling"),
        url(r"^venue/directions/", TemplateView.as_view(template_name="venue/directions.html"), name="directions"),
        url(r"^venue/getting-around/", TemplateView.as_view(template_name="venue/getting_around.html"), name="getting_around"),
        url(r"^venue/weather/", TemplateView.as_view(template_name="venue/weather.html"), name="weather"),
        url(r"^venue/explore/", TemplateView.as_view(template_name="venue/explore.html"), name="explore"),
        url(r"^venue/restaurants/", TemplateView.as_view(template_name="venue/restaurants.html"), name="restaurants"),
        url(r"^venue/bars/", TemplateView.as_view(template_name="venue/bars.html"), name="bars"),
        url(r"^venue/shopping/", TemplateView.as_view(template_name="venue/shopping.html"), name="shopping"),
        url(r"^venue/share-room/", TemplateView.as_view(template_name="venue/share_room.html"), name="share_room"),
        url(r"^venue/hotels/", TemplateView.as_view(template_name="venue/hotels.html"), name="hotels"),

        url(r"^finaid/", include("pycon.finaid.urls")),
        url(r"^pycon_api/", include("pycon.pycon_api.urls")),
        url(r"^schedule/", include("pycon.schedule.urls")),
        url(r"^profile/", include("pycon.profile.urls")),
        url(r"^tutorials/", include("pycon.tutorials.urls")),

        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposals/", include("symposion.proposals.urls")),
        url(r"^reviews/", include("symposion.reviews.urls")),
        url(r"^teams/", include("symposion.teams.urls")),
        url(r"^schedule/", include("symposion.schedule.urls")),
        url(r"^conference/", include("symposion.conference.urls")),

        url(r"^sponsors/", include("pycon.sponsorship.urls")),

        url(r"^boxes/", include("symposion.boxes.urls")),
        url(r"^sitemap/", TemplateView.as_view(template_name="static/sitemap.html"), name="sitemap"),
        url(r'^selectable/', include('selectable.urls')),
        url(r"^change_language/", symposion.views.change_language, name="change_language"),
        url(r"^", include("pycon.urls")),

        # This should be last, because it will create a new CMS page for
        # any unrecognized URL.
        url(r"^", include("symposion.cms.urls")),
    )))
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

symposion/boxes/models.py
from django.db import models

from django.contrib.auth.models import User

import reversion


class Box(models.Model):

    label = models.CharField(max_length=100, db_index=True)
    content = models.TextField(blank=True)

    created_by = models.ForeignKey(User, related_name="boxes")
    last_updated_by = models.ForeignKey(User, related_name="updated_boxes")

    def __unicode__(self):
        return self.label

    class Meta:
        verbose_name_plural = "boxes"


reversion.register(Box)

symposion/speakers/models.py
import datetime

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Speaker(models.Model):

    SESSION_COUNT_CHOICES = [
        (1, _(u"One")),
        (2, _(u"Two"))
    ]

    user = models.OneToOneField(User, null=True, related_name="speaker_profile")
    name = models.CharField(max_length=100,
                            help_text=_(u"As you would like it to appear in "
                                        u"the conference program."))
    biography = models.TextField(
        help_text=_(u"A little bit about you. 100 words or less, please. This "
                    u"will be used in print publications so please keep it "
                    u"simple, no links or formatting."))
    photo = models.ImageField(upload_to="speaker_photos", blank=True)
    twitter_username = models.CharField(
        max_length = 15,
        blank = True,
        help_text=_(u"Your Twitter account")
    )
    annotation = models.TextField() # staff only
    invite_email = models.CharField(max_length=200, unique=True, null=True, db_index=True)
    invite_token = models.CharField(max_length=40, db_index=True)
    created = models.DateTimeField(
        default = datetime.datetime.now,
        editable = False
    )
    sessions_preference = models.IntegerField(
        choices=SESSION_COUNT_CHOICES,
        null=True,
        blank=True,
        help_text=_(u"If you've submitted multiple talk proposals, please let "
                    u"us know if you only want to give one or if you'd like "
                    u"to give two talks.  For tutorials and posters, state "
                    u"similar preferences in the additional notes section of "
                    u"your proposals.")
    )

    admission = models.CharField(
        max_length = 15,
        blank = True,
        help_text=_(u"connpassNo/sponsor/Keynote")
    )

    def __unicode__(self):
        if self.user:
            return self.name
        else:
            return u"?"

    def get_absolute_url(self):
        return reverse("speaker_edit")

    @property
    def as_dict(self):
        return {
            'name': self.name,
            'email': self.email,
        }

    @property
    def email(self):
        if self.user is not None:
            return self.user.email
        else:
            return self.invite_email

    @property
    def all_presentations(self):
        presentations = []
        if self.presentations:
            for p in self.presentations.all():
                presentations.append(p)
            for p in self.copresentations.all():
                presentations.append(p)
        return presentations

symposion/boxes/forms.py
from django import forms

from markedit.widgets import MarkEdit

from symposion.boxes.models import Box


class BoxForm(forms.ModelForm):

    class Meta:
        model = Box
        fields = ["content"]
        widgets = {
            "content": MarkEdit(),
        }

symposion/cms/forms.py
from django import forms

from markedit.widgets import MarkEdit

from .models import Page


class PageForm(forms.ModelForm):

    class Meta:
        model = Page
        fields = ["title", "body", "body_fr", "path"]
        widgets = {
            "path": forms.HiddenInput(),
            "body": MarkEdit(),
            "body_fr": MarkEdit(),
        }


class FileUploadForm(forms.Form):

    file = forms.FileField()

symposion/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

import account.forms


class SignupForm(account.forms.SignupForm):

    first_name = forms.CharField()
    last_name = forms.CharField()
    email_confirm = forms.EmailField(label="Confirm Email")

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        del self.fields["username"]
        self.fields.keyOrder = [
            "email",
            "email_confirm",
            "first_name",
            "last_name",
            "password",
            "password_confirm"
        ]

    def clean_email_confirm(self):
        email = self.cleaned_data.get("email")
        email_confirm = self.cleaned_data["email_confirm"]
        if email:
            if email != email_confirm:
                raise forms.ValidationError("Email address must match previously typed email address")
        return email_confirm


def get_language_choices():
    # In settings, we had to mark the language names for translation using
    # a dummy ugettext to avoid circular imports, so now we need to actually
    # retrieve their translations
    return [(value, _(name))
            for value, name
            in settings.LANGUAGES]


class LanguageForm(forms.Form):
    language = forms.ChoiceField(
        choices=get_language_choices(),
        help_text=_(u"Change language for this session")
    )

symposion/proposals/forms.py
from django import forms
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _

from selectable import forms as selectable

from taggit.forms import TagField

from symposion.proposals.models import SupportingDocument

from .lookups import UserLookup

# @@@ generic proposal form


class AddSpeakerForm(forms.Form):

    email = selectable.AutoCompleteSelectField(
        lookup_class=UserLookup,
        allow_new=True,
        label=_("Email address"),
        required=True,
    )

    def __init__(self, *args, **kwargs):
        self.proposal = kwargs.pop("proposal")
        super(AddSpeakerForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        value = self.cleaned_data["email"]
        # django-selectable returns the user
        if isinstance(value, UserLookup.model):
            value = value.email
        if value == self.proposal.speaker.email:
            raise forms.ValidationError(
                _("You have submitted the Proposal author's email address. Please" \
                " select another email address.")
            )
        exists = self.proposal.additional_speakers.filter(
            Q(user=None, invite_email=value) |
            Q(user__email=value)
        ).exists()
        if exists:
            raise forms.ValidationError(
                _("This email address has already been invited to your talk proposal")
            )
        return value


class SupportingDocumentCreateForm(forms.ModelForm):

    class Meta:
        model = SupportingDocument
        fields = [
            "file",
            "description",
        ]


class ProposalTagsForm(forms.Form):
    tags = TagField(required=False,
                    help_text=_(u"Comma-separated list of tags"))

symposion/boxes/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.views.decorators.http import require_POST

from symposion.boxes.authorization import load_can_edit
from symposion.boxes.forms import BoxForm
from symposion.boxes.models import Box


# @@@ problem with this is that the box_edit.html and box_create.html won't have domain objects in context
def get_auth_vars(request):
    auth_vars = {}
    if request.method == "POST":
        keys = [k for k in request.POST.keys() if k.startswith("boxes_auth_")]
        for key in keys:
            auth_vars[key.replace("boxes_auth_", "")] = request.POST.get(key)
        auth_vars["user"] = request.user
    return auth_vars


@require_POST
def box_edit(request, label):
    
    if not load_can_edit()(request, **get_auth_vars(request)):
        return HttpResponseForbidden()
    
    next = request.GET.get("next")
    
    try:
        box = Box.objects.get(label=label)
    except Box.DoesNotExist:
        box = None
    
    form = BoxForm(request.POST, instance=box, prefix=label)

    if form.is_valid():
        if box is None:
            box = form.save(commit=False)
            box.label = label
            box.created_by = request.user
            box.last_updated_by = request.user
            box.save()
        else:
            form.save()
        return redirect(next)

symposion/cms/views.py
from django.conf import settings
from django.db import transaction
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import static

from django.contrib.auth.decorators import login_required
from .models import Page, File
from .forms import PageForm, FileUploadForm


def can_edit(page, user):
    if page and page.is_community:
        return True
    else:
        return user.has_perm("cms.change_page")


def can_upload(user):
    if user.is_staff or user.is_superuser:
        return True
    return False


def page(request, path):
    
    try:
        page = Page.published.get(path=path)
    except Page.DoesNotExist:
        page = None
    
    editable = can_edit(page, request.user)
    
    if page is None:
        if editable:
            return redirect("cms_page_edit", path=path)
        else:
            raise Http404

    use_french = request.LANGUAGE_CODE.startswith('fr') and page.body_fr

    return render(request, "cms/page_detail.html", {
        "page": page,
        "use_french": use_french,
        "editable": editable,
    })


@login_required
def page_edit(request, path):
    
    try:
        page = Page.published.get(path=path)
    except Page.DoesNotExist:
        page = None
    
    if not can_edit(page, request.user):
        raise Http404
    
    if request.method == "POST":
        form = PageForm(request.POST, instance=page)
        if form.is_valid():
            page = form.save(commit=False)
            page.path = path
            page.save()
            return redirect(page)
        else:
            print form.errors
    else:
        form = PageForm(instance=page, initial={"path": path})
    
    return render(request, "cms/page_edit.html", {
        "path": path,
        "form": form
    })


def file_index(request):
    if not can_upload(request.user):
        raise Http404
    
    ctx = {
        "files": File.objects.all(),
    }
    return render(request, "cms/file_index.html", ctx)


def file_create(request):
    if not can_upload(request.user):
        raise Http404
    
    if request.method == "POST":
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            with transaction.commit_on_success():
                kwargs = {
                    "file": form.cleaned_data["file"],
                }
                File.objects.create(**kwargs)
            return redirect("file_index")
    else:
        form = FileUploadForm()
    
    ctx = {
        "form": form,
    }
    return render(request, "cms/file_create.html", ctx)


def file_download(request, pk, *args):
    file = get_object_or_404(File, pk=pk)
    
    if getattr(settings, "USE_X_ACCEL_REDIRECT", False):
        response = HttpResponse()
        response["X-Accel-Redirect"] = file.file.url
        # delete content-type to allow Gondor to determine the filetype and
        # we definitely don't want Django's default :-)
        del response["content-type"]
    else:
        response = static.serve(request, file.file.name, document_root=settings.MEDIA_ROOT)
    
    return response


def file_delete(request, pk):
    if not can_upload(request.user):
        raise Http404
    
    file = get_object_or_404(File, pk=pk)
    if request.method == "POST":
        file.delete()
        # @@@ message
    return redirect("file_index")

symposion/conference/views.py
from django.http import Http404
from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


@login_required
def user_list(request):
    
    if not request.user.is_staff:
        raise Http404()
    
    return render(request, "conference/user_list.html", {
        "users": User.objects.all(),
    })

symposion/templates/_account_bar.html
{% load url from future %}
{% load account_tags %}
{% load i18n %}

<div class="row">
    <div class="pull-right">
        {% if user.is_authenticated %}
            {% if user.is_staff %}
                <a href="{% url 'admin:index' %}" class="action">{% trans "Admin" %}</a> |
            {% endif %}
            <a href="{% url 'dashboard' %}">{% trans "Dashboard" %}</a>
            |
            <a href="{% url 'account_settings' %}">{% trans "Settings" %}</a>
            |
            <form action="{% url 'account_logout' %}" method="post">{% csrf_token %}
                <button type="submit">{% trans "Log out" %}</button>
            </form>
            {% if request.user.get_full_name%}
            <span>
            | 
                <i class="icon icon-user"></i>
                <strong>{% user_display request.user %}</strong>
            </span>
            {% endif %}
        {% else %}
            <a href="{% url 'account_login' %}">{% trans "Log in" %}</a>
            |
            <a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a>
        {% endif %}
    </div>
</div>

symposion/templates/_sponsorship_link.html
{% load i18n %}

<div>
    <span class="bracket-left"></span>
    <span class="in-brackets"><em>{% trans "Sponsorship available." %}</em> <a href="{% url 'cms_page' "sponsors/prospectus/" %}" class="more">Learn more</a>.
    </span>
    <span class="bracket-right"></span>
</div>

symposion/templates/auth_base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block body_class %}auth{% endblock %}

{% block body_outer %}
    <div class="row">
        <div class="span12">
            <div class="page-head">
                <h1>{% block page_title %}{% endblock %}</h1>
                {% block breadcrumbs %}
                    <ul class="breadcrumb">
                        <li><a href="{% url 'dashboard' %}">{% trans "Dashboard" %}</a></li>
                    </ul>
                {% endblock %}
            </div>
            <div class="box">
                <div class="box-content">
                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_script %}
    <script type="text/javascript">
        $(function() {
            // Prepend @ symbol to any twitter username fields
            var twitterInput = $("#id_twitter_username");
            if (twitterInput) {
                var wrapperdiv = $("<div class='input-prepend'/>");
                var twitterInput = $("#id_twitter_username");

                twitterInput.parent("div.controls").prepend(wrapperdiv);
                wrapperdiv.append("<span class='add-on'>@</span>", twitterInput);
            };
        });
    </script>
{% endblock %}

symposion/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}
{% load cache %}
{% load compress %}
{% load sponsorship_tags %}
{% load thumbnail %}
{% load boxes_tags %}
{% load biblion_tags %}

{% block head_title_base %}PyCon 2014 in Montr&#233;al | April 9th &ndash; April 17th{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    <div class="banner">
        <div class="container" itemscope itemtype="http://data-vocabulary.org/Event">
            <div class="row">
                <div class="span7">
                    <h1 itemprop="summary"><a href="/" class="logo">PyCon 2014</a></h1>
                    <h2><span itemprop="locality">Santa Clara</span>, <span itemprop="region">CA</span>, <time itemprop="startDate" datetime="2014-3-13">March 13</time>&ndash;<time itemprop="endDate" datetime="2014-3-21">21</time></h2>
                </div>
                <div class="span5">
                    <p class="intro" itemprop="description">
                        The largest annual gathering<br />
                        for the community using and developing<br />
                        the open-source<br />
                        <strong>Python programming language</strong>
                    </p>
                </div>
                <span itemprop="geo" itemscope itemtype="http://data-vocabulary.org/​Geo">
                    <meta itemprop="latitude" content="37.405364" />
                    <meta itemprop="longitude" content="-121.975408" />
                </span>
            </div>
            <div class="dotted-ln"></div>
            <div class="row">
                <div class="span12">
                    <h4>Change the future - education, outreach, politeness, respect, tenacity and vision</h4>
                </div>
            </div>
            <div class="dotted-ln"></div>
            <div class="row">
                <div class="span4">
                    <ul class="unstyled">
                        <li><a href="#"><span>Tutorials:</span>  March 13&ndash;14</a></li>
                        <li><a href="#"><span>Main Conference:</span>  March 15&ndash;17</a></li>
                        <li><a href="#"><span>Development Sprints:</span>  March 18&ndash;21</a></li>
                    </ul>
                </div>
                <div class="span5">
                    <div class="presented">
                        <div class="bdr"></div>
                        <h6>Presented By</h6>

                        {% cache 600 "homepage-sponsors-diamond" %}
                            {% sponsors "diamond" as diamond_sponsors %}

                            {% if diamond_sponsors|length == 0 %}
                                {% include "_sponsorship_link.html" %}
                            {% else %}
                                {% for sponsor in diamond_sponsors %}
                                    <a href="{{ sponsor.external_url }}">
                                        <img src="{% thumbnail sponsor.website_logo '200x120' %}" alt="{{ sponsor.name }}" class="diamond-sponsors" />
                                    </a>
                                {% endfor %}

                                {% if diamond_sponsors|length == 1 %}
                                    <div class="sponsorship-link">
                                        {% include "_sponsorship_link.html" %}
                                    </div>
                                {% endif %}
                            {% endif %}
                        {% endcache %}
                        <div class="bdr bdr-r"></div>
                    </div>
                </div>
                <div class="span3 tickets-info" itemprop="tickets" itemscope itemtype="http://data-vocabulary.org/Offer">
                    <div class="tickets"></div>
                    <h6>Registration</h6>
                  {% comment %}
                    <p>
                        <strong>Now Open!</strong> <br />
                        <a href="{% url 'registration_start' %}" itemprop="offerurl">Click here to register.</a>
                    </p>
                    {% endcomment %}
                </div>
            </div>
            <div class="dotted-ln no-mrg-btm"></div>
        </div>
    </div>
{% endblock %}

{% block body_outer %}
<div class="row">
    <div class="span12 sponsor-crawl">
        {% cache 600 "homepage-sponsor-slider" %}
            <h3 class="scroll-title">Sponsors</h3>
            {% sponsors "diamond" as diamond_sponsors %}
            {% if diamond_sponsors|length > 1 %}
                <div class="sponsorship-link">
                    {% include "_sponsorship_link.html" %}
                </div>
            {% endif %}
            <div id="sponsorslider" class="carousel slide">
              <!-- Carousel items -->
              <div class="carousel-inner">
              {% sponsors as all_sponsors %}
                {# sponsors without levels, 21 per each slide #}
                {% for sponsor in all_sponsors %}
                    {% if forloop.first or forloop.counter0|divisibleby:"21" %}
                        <div class="item {% if forloop.first %}active{% endif %}" style="margin: auto;">
                    {% endif %}

                    <a href="{{ sponsor.external_url }}" title="{{ sponsor.name }}">
                        <div class="sponsor-scroll-item" style="background-image: url('{% thumbnail sponsor.website_logo '95x95' %}')" data-background-2x="{% thumbnail sponsor.website_logo '190x190' %}"></div>
                    </a>
                    {% if forloop.counter|divisibleby:"21" or forloop.last %}</div>{% endif %}
                {% endfor %}
              </div>
              <!-- Carousel nav -->
              <nav id="slider-nav">
                {% for sponsor in all_sponsors %}
                    {% if forloop.first or forloop.counter0|divisibleby:"21" %}
                        <a href="#" class="{% if forloop.first %}activeSlide{% endif %}"></a>
                    {% endif %}
                {% endfor %}
              </nav>
            </div>
        {% endcache %}
    </div>

    {% latest_blog_posts as posts %}
    <div class="span8">
        <h3>Announcements</h3>
            {% for post in posts %}
                <div class="blog-post">
                    <div class="date">
                        <span class="month">{{ post.published|date:"M" }}</span> {{ post.published|date:"n" }}
                        <span class="year">{{ post.published|date:"Y" }}</span>
                    </div>
                    <div class="post-content">
                        <h2>{{ post.title }}</h2>
                        <p class="post_dateline">by <span class="author">{{ post.author.get_full_name }}</span></p>
                        <div class="teaser">{{ post.teaser_html|safe }}</div>
                    </div>
                </div>
            {% empty %}
                <p>No announcements have been published.</p>
            {% endfor %}
    </div>
    <div class="span4">
        {% box "homepage-about" %}
    </div>
</div>
{% endblock %}

{% block extra_body %}
  {% compress js %}
    <script type="text/javascript">
        $(function(){
            var slider = $("#sponsorslider").carousel({interval: 7000});
            slider.bind("slid", function() {
                var index = $(this).find(".active").index();
                $(this).find("#slider-nav a").removeClass("activeSlide").eq(index).addClass("activeSlide");
            });
            $("#slider-nav a").click(function(e){
                var index = $(this).index();
                slider.carousel(index);
                e.preventDefault();
            });

            var retina = window.devicePixelRatio > 1.5 ? true : false;
            if (retina) {
                $("div.sponsor-scroll-item").each(function() {
                    var retinaimage = $(this).data("background-2x");
                    $(this).css("background-image", "url("+retinaimage+")");
                    // preload image
                    $('<img/>')[0].src = retinaimage;
                })
            };
        });
    </script>
  {% endcompress %}
{% endblock %}