localeurlcustom/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from localeurlcustom.views import change_locale

urlpatterns = patterns('',
	url(r'^change/', change_locale, name='localeurl_change_locale'),
)

pycon/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url('program_export/', views.program_export, name='program_export'),
)

symposion/cms/urls.py
from django.conf.urls.defaults import url, patterns

PAGE_RE = r"(([\w-]{1,})(/[\w-]{1,})*)/"

urlpatterns = patterns("symposion.cms.views",
    url(r"^files/$", "file_index", name="file_index"),
    url(r"^files/create/$", "file_create", name="file_create"),
    url(r"^files/(\d+)/([^/]+)$", "file_download", name="file_download"),
    url(r"^files/(\d+)/delete/$", "file_delete", name="file_delete"),
    url(r"^(?P<path>%s)_edit/$" % PAGE_RE, "page_edit", name="cms_page_edit"),
    url(r"^(?P<path>%s)$" % PAGE_RE, "page", name="cms_page"),
)

symposion/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static

from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

admin.autodiscover()

import symposion.views

# from pinax.apps.account.openid_consumer import PinaxConsumer


URL_PREFIX = settings.CONFERENCE_URL_PREFIXES[settings.CONFERENCE_ID]


urlpatterns = patterns("",
    url(r"^$", RedirectView.as_view(url="/%s/" % URL_PREFIX)),
    url(r"^%s/" % URL_PREFIX, include(patterns("",
        url(r"^$", TemplateView.as_view(template_name="homepage.html"),
            name="home"),
        url(r"^admin/", include(admin.site.urls)),
        url(r"^account/signup/$", symposion.views.SignupView.as_view(), name="account_signup"),
        url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
        url(r"^account/social/", include("social_auth.urls")),
        url(r"^account/associations/", include("symposion.social_auth.urls")),
        url(r"^account/", include("account.urls")),
        url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
        url(r"^blog/", include("biblion.urls")),
        url(r"^force500/", lambda request: xxx),

        url(r"^registration/", include("pycon.registration.urls")),

        url(r"^venue/$", TemplateView.as_view(template_name="venue/detail.html"), name="venue_detail"),
        url(r"^venue/traveling/", TemplateView.as_view(template_name="venue/traveling.html"), name="traveling"),
        url(r"^venue/directions/", TemplateView.as_view(template_name="venue/directions.html"), name="directions"),
        url(r"^venue/getting-around/", TemplateView.as_view(template_name="venue/getting_around.html"), name="getting_around"),
        url(r"^venue/weather/", TemplateView.as_view(template_name="venue/weather.html"), name="weather"),
        url(r"^venue/explore/", TemplateView.as_view(template_name="venue/explore.html"), name="explore"),
        url(r"^venue/restaurants/", TemplateView.as_view(template_name="venue/restaurants.html"), name="restaurants"),
        url(r"^venue/bars/", TemplateView.as_view(template_name="venue/bars.html"), name="bars"),
        url(r"^venue/shopping/", TemplateView.as_view(template_name="venue/shopping.html"), name="shopping"),
        url(r"^venue/share-room/", TemplateView.as_view(template_name="venue/share_room.html"), name="share_room"),
        url(r"^venue/hotels/", TemplateView.as_view(template_name="venue/hotels.html"), name="hotels"),

        url(r"^finaid/", include("pycon.finaid.urls")),
        url(r"^pycon_api/", include("pycon.pycon_api.urls")),
        url(r"^schedule/", include("pycon.schedule.urls")),
        url(r"^profile/", include("pycon.profile.urls")),
        url(r"^tutorials/", include("pycon.tutorials.urls")),

        url(r"^speaker/", include("symposion.speakers.urls")),
        url(r"^proposals/", include("symposion.proposals.urls")),
        url(r"^reviews/", include("symposion.reviews.urls")),
        url(r"^teams/", include("symposion.teams.urls")),
        url(r"^schedule/", include("symposion.schedule.urls")),
        url(r"^conference/", include("symposion.conference.urls")),

        url(r"^sponsors/", include("pycon.sponsorship.urls")),

        url(r"^boxes/", include("symposion.boxes.urls")),
        url(r"^sitemap/", TemplateView.as_view(template_name="static/sitemap.html"), name="sitemap"),
        url(r'^selectable/', include('selectable.urls')),
        url(r"^change_language/", symposion.views.change_language, name="change_language"),
        url(r"^", include("pycon.urls")),

        # This should be last, because it will create a new CMS page for
        # any unrecognized URL.
        url(r"^", include("symposion.cms.urls")),
    )))
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

symposion/proposals/models.py
import datetime
import os
import uuid

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User

import json
import reversion

from model_utils.managers import InheritanceManager
from taggit.managers import TaggableManager

from symposion.conference.models import Section


class ProposalSection(models.Model):
    """
    configuration of proposal submissions for a specific Section.

    a section is available for proposals iff:
      * it is after start (if there is one) and
      * it is before end (if there is one) and
      * closed is NULL or False
    """

    section = models.OneToOneField(Section)

    start = models.DateTimeField(null=True, blank=True,
                                 help_text=_("When submissions open"))
    end = models.DateTimeField(null=True, blank=True,
                               help_text=_("When submissions close"))
    closed = models.NullBooleanField()
    published = models.NullBooleanField()

    @classmethod
    def available(cls):
        now = datetime.datetime.now()
        return cls._default_manager.filter(
            Q(start__lt=now) | Q(start=None),
            Q(end__gt=now) | Q(end=None),
            Q(closed=False) | Q(closed=None),
        )

    def is_available(self):
        if self.closed:
            return False
        now = datetime.datetime.now()
        if self.start and self.start > now:
            return False
        if self.end and self.end < now:
            return False
        return True

    def __unicode__(self):
        return self.section.name


class ProposalKind(models.Model):
    """
    e.g. talk vs panel vs tutorial vs poster

    Note that if you have different deadlines, reviewers, etc. you'll want
    to distinguish the section as well as the kind.
    """

    section = models.ForeignKey(Section, related_name="proposal_kinds")

    name = models.CharField(_("Name"), max_length=100)
    slug = models.SlugField()

    def __unicode__(self):
        return self.name


class ProposalBase(models.Model):

    objects = InheritanceManager()

    kind = models.ForeignKey(ProposalKind)

    title = models.CharField(_("Title"), max_length=100)
    description = models.TextField(
        _("Description"),
        max_length=200,  # @@@ need to enforce 400 in UI <= Can not change? I did it to 200.
        help_text=_("Please write up to 100 words. "
                    "This is published pamphlet when it is accepted.")
    )
    abstract = models.TextField(
        _("Details Abstract"),
        help_text=_("Please write detailed contents of your presentation to a maximum extent. "
                    "This is published web site when it is accepted.")
    )
    additional_notes = models.TextField(
        _("Additional Notes"),
        blank=True,
        help_text=_("Anything else you'd like the program committee to know "
                    "when making their selection: your past speaking "
                    "experience, open source community experience, etc. "
                    "This is not published. it is referenced by review.")
    )
    submitted = models.DateTimeField(
        default=datetime.datetime.now,
        editable=False,
    )
    speaker = models.ForeignKey("speakers.Speaker", related_name="proposals")
    additional_speakers = models.ManyToManyField("speakers.Speaker", through="AdditionalSpeaker", blank=True)
    cancelled = models.BooleanField(default=False)
    tags = TaggableManager(blank=True)
    language = models.CharField(
        max_length=2,
        verbose_name=_("Language"),
        default=settings.LANGUAGES[0][0],
        choices=settings.LANGUAGES,
    )

    def __unicode__(self):
        return self.title

    def can_edit(self):
        if hasattr(self, "presentation") and self.presentation:
            return False
        else:
            return True

    def get_tags_display(self):
        # No idea why django-taggit doesn't offer this itself
        return u", ".join(tag.name for tag in self.tags.all())

    @property
    def section(self):
        return self.kind.section

    @property
    def speaker_email(self):
        return self.speaker.email

    @property
    def number(self):
        return str(self.pk).zfill(3)

    @property
    def status(self):
        try:
            return self.result.status
        except ObjectDoesNotExist:
            return 'undecided'

    def as_dict(self, details=False):
        """Return a dictionary representation of this proposal."""

        # Put together the base dict.
        answer = {
            'id': self.id,
            'speakers': [i.as_dict for i in self.speakers()],
            'status': self.status,
            'title': self.title,
        }

        # Include details iff they're requested.
        if details:
            answer['details'] = {
                'abstract': self.abstract,
                'description': self.description,
                'notes': self.additional_notes,
            }

            # If there is extra data that has been set, include it also.
            try:
                answer['extra'] = json.loads(self.data.data)
            except ObjectDoesNotExist:
                pass

        # Return the answer.
        return answer

    def speakers(self):
        yield self.speaker
        for speaker in self.additional_speakers.exclude(additionalspeaker__status=AdditionalSpeaker.SPEAKING_STATUS_DECLINED):
            yield speaker

    def notification_email_context(self):
        return {
            "title": self.title,
            "speaker": self.speaker.name,
            "speakers": ', '.join([x.name for x in self.speakers()]),
            "kind": self.kind.name,
        }


reversion.register(ProposalBase)


class AdditionalSpeaker(models.Model):

    SPEAKING_STATUS_PENDING = 1
    SPEAKING_STATUS_ACCEPTED = 2
    SPEAKING_STATUS_DECLINED = 3

    SPEAKING_STATUS = [
        (SPEAKING_STATUS_PENDING, _("Pending")),
        (SPEAKING_STATUS_ACCEPTED, _("Accepted")),
        (SPEAKING_STATUS_DECLINED, _("Declined")),
    ]

    speaker = models.ForeignKey("speakers.Speaker")
    proposalbase = models.ForeignKey(ProposalBase)
    status = models.IntegerField(choices=SPEAKING_STATUS, default=SPEAKING_STATUS_PENDING)

    class Meta:
        db_table = "proposals_proposalbase_additional_speakers"
        unique_together = ("speaker", "proposalbase")


def uuid_filename(instance, filename):
    ext = filename.split(".")[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join("document", filename)


class SupportingDocument(models.Model):

    proposal = models.ForeignKey(ProposalBase, related_name="supporting_documents")

    uploaded_by = models.ForeignKey(User)
    created_at = models.DateTimeField(default=datetime.datetime.now)

    file = models.FileField(upload_to=uuid_filename)
    description = models.CharField(max_length=140)

    def download_url(self):
        return reverse("proposal_document_download", args=[self.pk, os.path.basename(self.file.name).lower()])

symposion/boxes/forms.py
from django import forms

from markedit.widgets import MarkEdit

from symposion.boxes.models import Box


class BoxForm(forms.ModelForm):

    class Meta:
        model = Box
        fields = ["content"]
        widgets = {
            "content": MarkEdit(),
        }

symposion/boxes/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.views.decorators.http import require_POST

from symposion.boxes.authorization import load_can_edit
from symposion.boxes.forms import BoxForm
from symposion.boxes.models import Box


# @@@ problem with this is that the box_edit.html and box_create.html won't have domain objects in context
def get_auth_vars(request):
    auth_vars = {}
    if request.method == "POST":
        keys = [k for k in request.POST.keys() if k.startswith("boxes_auth_")]
        for key in keys:
            auth_vars[key.replace("boxes_auth_", "")] = request.POST.get(key)
        auth_vars["user"] = request.user
    return auth_vars


@require_POST
def box_edit(request, label):
    
    if not load_can_edit()(request, **get_auth_vars(request)):
        return HttpResponseForbidden()
    
    next = request.GET.get("next")
    
    try:
        box = Box.objects.get(label=label)
    except Box.DoesNotExist:
        box = None
    
    form = BoxForm(request.POST, instance=box, prefix=label)

    if form.is_valid():
        if box is None:
            box = form.save(commit=False)
            box.label = label
            box.created_by = request.user
            box.last_updated_by = request.user
            box.save()
        else:
            form.save()
        return redirect(next)

symposion/cms/views.py
from django.conf import settings
from django.db import transaction
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import static

from django.contrib.auth.decorators import login_required
from .models import Page, File
from .forms import PageForm, FileUploadForm


def can_edit(page, user):
    if page and page.is_community:
        return True
    else:
        return user.has_perm("cms.change_page")


def can_upload(user):
    if user.is_staff or user.is_superuser:
        return True
    return False


def page(request, path):
    
    try:
        page = Page.published.get(path=path)
    except Page.DoesNotExist:
        page = None
    
    editable = can_edit(page, request.user)
    
    if page is None:
        if editable:
            return redirect("cms_page_edit", path=path)
        else:
            raise Http404

    use_french = request.LANGUAGE_CODE.startswith('fr') and page.body_fr

    return render(request, "cms/page_detail.html", {
        "page": page,
        "use_french": use_french,
        "editable": editable,
    })


@login_required
def page_edit(request, path):
    
    try:
        page = Page.published.get(path=path)
    except Page.DoesNotExist:
        page = None
    
    if not can_edit(page, request.user):
        raise Http404
    
    if request.method == "POST":
        form = PageForm(request.POST, instance=page)
        if form.is_valid():
            page = form.save(commit=False)
            page.path = path
            page.save()
            return redirect(page)
        else:
            print form.errors
    else:
        form = PageForm(instance=page, initial={"path": path})
    
    return render(request, "cms/page_edit.html", {
        "path": path,
        "form": form
    })


def file_index(request):
    if not can_upload(request.user):
        raise Http404
    
    ctx = {
        "files": File.objects.all(),
    }
    return render(request, "cms/file_index.html", ctx)


def file_create(request):
    if not can_upload(request.user):
        raise Http404
    
    if request.method == "POST":
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            with transaction.commit_on_success():
                kwargs = {
                    "file": form.cleaned_data["file"],
                }
                File.objects.create(**kwargs)
            return redirect("file_index")
    else:
        form = FileUploadForm()
    
    ctx = {
        "form": form,
    }
    return render(request, "cms/file_create.html", ctx)


def file_download(request, pk, *args):
    file = get_object_or_404(File, pk=pk)
    
    if getattr(settings, "USE_X_ACCEL_REDIRECT", False):
        response = HttpResponse()
        response["X-Accel-Redirect"] = file.file.url
        # delete content-type to allow Gondor to determine the filetype and
        # we definitely don't want Django's default :-)
        del response["content-type"]
    else:
        response = static.serve(request, file.file.name, document_root=settings.MEDIA_ROOT)
    
    return response


def file_delete(request, pk):
    if not can_upload(request.user):
        raise Http404
    
    file = get_object_or_404(File, pk=pk)
    if request.method == "POST":
        file.delete()
        # @@@ message
    return redirect("file_index")

symposion/conference/views.py
from django.http import Http404
from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


@login_required
def user_list(request):
    
    if not request.user.is_staff:
        raise Http404()
    
    return render(request, "conference/user_list.html", {
        "users": User.objects.all(),
    })

symposion/templates/reviews/_result_notification_prepare_help.html
    <b>Body</b> may include the following variables which will be substituted in the email with a value
    specific to each proposal:
<ul>
    <li><code>{% templatetag openvariable %} proposal.title {% templatetag closevariable %}</code> e.g. {{ proposals.0.title }}
    <li><code>{% templatetag openvariable %} proposal.kind {% templatetag closevariable %}</code> e.g. {{ proposals.0.kind }}
    <li><code>{% templatetag openvariable %} proposal.speaker {% templatetag closevariable %}</code> e.g. {{ proposals.0.speaker }}
    <li><code>{% templatetag openvariable %} proposal.speakers {% templatetag closevariable %}</code> e.g. {% for speaker in proposals.0.speakers %}{{ speaker.name }}{% if not forloop.last %}, {% endif %}{% endfor %}
</ul>

symposion/templates/reviews/_review_table.html
{% load i18n %}
{% load compress %}
<table class="table table-striped table-bordered table-reviews">
    <thead>
        <th>{% trans "Voted" %}</th>
        <th>#</th>
        <th>{% trans "Speaker / Title" %}</th>
        <th>{% trans "Category" %}</th>
        <th>{% trans "Language" %}</th>
        <th>{% trans "Tags" %}</th>
        <th><i class="icon-comment-alt"></i></th>
        <th>+1</th>
        <th>+0</th>
        <th>-0</th>
        <th>-1</th>
        <th>{% trans "Online Result Status" %}</th>
        <th>
            {% trans "Overall Status" %}<br>
            {% if can_manage %}
                {% trans "Update Overall Status" %}
            {% endif %}

        </th>
    </thead>

    <tbody>
        {% for proposal in proposals %}
            <tr class="{{ proposal.user_vote_css }} {% if proposal.cancelled == True %}canceled{% endif %}">
                <td>{% if proposal.user_vote == None %}<span style="color: red">No Vote</span>{% else %} Voted {% endif %}</td>
                <td>{{ proposal.number }} {{ proposal.cancelled }} </td>
                <td>
                    <a href="{% url 'review_detail' proposal.pk %}">
                        <small><strong>{{ proposal.speaker }}</strong></small>
                        <br />
                        {{ proposal.title }}
                    </a>
                </td>
                <td>{{ proposal.category }}</td>
                <td>{{ proposal.get_language_display }}</td>
                <td>{{ proposal.get_tags_display }}</td>
                <td>{{ proposal.comment_count }}</td>
                <td>{{ proposal.plus_one }}</td>
                <td>{{ proposal.plus_zero }}</td>
                <td>{{ proposal.minus_zero }}</td>
                <td>{{ proposal.minus_one }}</td>
                <td>
                    {% with proposal.result.status as status %}
                        <div class="{{ status }}">
                            {% if status != "undecided" %}
                                <span>{{ status }}</span>
                            {% else%}
                                {% if proposal.cancelled == True %}canceled{% endif %}
                            {% endif %}
                        </div>
                    {% endwith %}
                
                </td>
                <td>
                    {{ proposal.get_overall_status_display }}
                    {% if can_manage %}
                        <br><br>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="pk" value="{{ proposal.pk }}" />
                            <select name="status" onChange="this.form.submit();">
                                {% for k, v in status_options %}
                                    <option value="{{ k }}" {% if proposal.overall_status == k %}selected="selected"{% endif %}>
                                        {{ v }}
                                    </option>
                                {% endfor %}
                            </select>
                        </form>

                    {% endif %}

                </td>
                
            </tr>

        {% endfor %}
    </tbody>
</table>

<style>
    .no-vote {
        background-color: #f4f379 !important;
    }
</style>


{% compress js %}
<script src="{{ STATIC_URL }}datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}tabletools/js/TableTools.min.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}datatables/js/dataTables.bootstrap.js" type="text/javascript"></script>
<script type="text/javascript">

    $(function() {
        var $canceled = $(".canceled");
        $canceled.hide();

        $(".tip").tooltip();
        var cols = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11{% if request.user.is_superuser %}, 13, 14{% endif %}];
        $("table.table-reviews").dataTable({
            "sDom": "<'row'<'span3'l><'span3'T><'span4'f>r>t<'row'<'span3'i><'span5'p>>",
            "sPaginationType": "bootstrap",
            "bStateSave": true,
            "oTableTools": {
                "aButtons": [
                    {
                        "sExtends": "copy",
                        "mColumns": cols
                    },
                    {
                        "sExtends": "csv",
                        "mColumns": cols,
                        "sFileName": "{{ section }} Review.csv"
                    },
                    {
                        "sExtends": "print",
                        "mColumns": cols
                    },
                    {
                        "sExtends": "text",
                        "sButtonText": "Show all",
                        "fnClick": function ( nButton, oConfig, oFlash ) {
                            $canceled.toggle();
                        }
                    }
                ],
                "sSwfPath": "{{ STATIC_URL }}tabletools/swf/copy_csv_xls.swf"
            }
        });
    });
</script>
{% endcompress %}

symposion/templates/reviews/access_not_permitted.html
{% extends "reviews/base.html" %}

{% block body %}
    <h1>Access Not Permitted</h1>
    
    <p>
        Sorry, you do not have permission to access this page. If you 
        believe this is a bug, please contact us immediately.
    </p>
{% endblock %}

symposion/templates/reviews/base.html
{% extends "site_base.html" %}

{% load compress %}
{% load i18n %}
{% load sitetree %}

{% block extra_style %}
  {% compress css %}
    <style type="text/css">
        div.dataTables_length label {
            float: left;
            text-align: left;
        }

        div.dataTables_length select {
            width: 75px;
        }

        div.dataTables_filter label {
            float: right;
        }

        div.dataTables_info {
            padding-top: 8px;
        }

        div.dataTables_paginate {
            float: right;
            margin: 0;
        }

        table.table {
            clear: both;
            margin-bottom: 6px !important;
            background-color: white;
        }

        table.table thead .sorting,
        table.table thead .sorting_asc,
        table.table thead .sorting_desc,
        table.table thead .sorting_asc_disabled,
        table.table thead .sorting_desc_disabled {
            cursor: pointer;
            *cursor: hand;
        }

        {% comment %}
        table.table thead .sorting { background: url('{{ STATIC_URL }}datatables/images/sort_both.png') no-repeat center right; }
        table.table thead .sorting_asc { background: url('{{ STATIC_URL }}datatables/images/sort_asc.png') no-repeat center right; }
        table.table thead .sorting_desc { background: url('{{ STATIC_URL }}datatables/images/sort_desc.png') no-repeat center right; }

        table.table thead .sorting_asc_disabled { background: url('{{ STATIC_URL }}datatables/images/sort_asc_disabled.png') no-repeat center right; }
        table.table thead .sorting_desc_disabled { background: url('{{ STATIC_URL }}datatables/images/sort_desc_disabled.png') no-repeat center right; }
        {% endcomment %}

        table.dataTable th:active {
            outline: none;
        }
    </style>
  {% endcompress %}
{% endblock %}

{% block body_class %}reviews{% endblock %}

{% block body_base %}
    <div class="container">

        {% include "_messages.html" %}

        {% block breadcrumbs %}
            {% sitetree_breadcrumbs from "main" %}
        {% endblock %}

        <div class="row">
            <div class="span2">
                {% block sidebar %}
                    <ul class="nav nav-list well">
                        {% for section in review_sections %}
                            <li class="nav-header">
                                {{ section }}
                            </li>
                            <li>
                                <a href="{% url 'review_section' section.section.slug %}">
                                    {% trans "Reviews" %}
                                </a>
                            </li>
                            {% comment %}
                            <li>
                                <a href="{% url 'review_section_assignments' section.section.slug %}">
                                    {% trans "Your Assignments" %}
                                </a>
                            </li>
                            {% endcomment %}
                            <li>
                                <a href="{% url 'review_status' section.section.slug %}">
                                    {% trans "Voting Status" %}
                                </a>
                            </li>
                            {% if request.user.is_staff %}
                                <li>
                                    <a href="{% url 'result_notification' section.section.slug 'accepted' %}">{% trans "Result Notification" %}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endblock %}
            </div>
            <div class="span10">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

symposion/templates/reviews/result_notification_prepare.html
{% extends "reviews/base.html" %}

{% load i18n %}

{% block body %}
    <h1>Result Notification Prepare</h1>
    
    <div class="row">
        <div class="span4">
            <h2>Proposals</h2>
            <table class="table table-striped table-compact">
                {% for proposal in proposals %}
                    <tr>
                        <td>
                            <strong>{{ proposal.speaker }}</strong> ({{ proposal.speaker.email }})
                            <br />
                            {{ proposal.title }}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="span6">
            <h2>Email</h2>
            
            <form method="post" action="{% url 'result_notification_send' section_slug status %}">
                
                {% csrf_token %}
                
                <label>From Address</label>
                <input type="text" name="from_address" class="span5" value="{{ notification_template.from_address }}" />
                <br/>
                <label>Subject</label>
                <input type="text" name="subject" class="span5" value="{{ notification_template.subject }}" />
                <br/>
                <label>Body</label>
                <textarea class="span5" rows="10" name="body">{{ notification_template.body }}</textarea>
                <br/>
                <input type="hidden" name="notification_template" value="{{ notification_template.pk }}" />
                <input type="hidden" name="proposal_pks" value="{{ proposal_pks }}" />
                
                {% include "reviews/_result_notification_prepare_help.html" %}
                
                <button type="submit" class="btn btn-primary">Send {{ proposals|length }} Email{{ proposals|length|pluralize }}</button>
                <a class="btn" href="{% url 'result_notification' section_slug status %}">Cancel</a>
            </form>
        </div>
    </form>
{% endblock %}

symposion/templates/reviews/review_admin.html
{% extends "reviews/base.html" %}

{% block body %}
    <h1>Reviewers</h1>
    
    <table class="table table-striped">
        <tr>
            <th>
                Reviewer
            </th>
            <th>
                Proposals<br/>Reviewed
            </td>
            <th>
                Comments
            </th>
            <th>
                +1
            </th>
            <th>
                +0
            </th>
            <th>
                &minus;0
            </th>
            <th>
                &minus;1
            </th>
        </tr>
        {% for reviewer in reviewers %}
        <tr>
            <td>
                <a href="{% url 'review_list_user' section_slug reviewer.pk %}">{{ reviewer.get_full_name }}</a>
            </td>
            <td>
                {{ reviewer.total_votes }}
            </td>
            <td>
                {{ reviewer.comment_count }}
            </td>
            <td>
                {{ reviewer.plus_one }}
            </td>
            <td>
                {{ reviewer.plus_zero }}
            </td>
            <td>
                {{ reviewer.minus_zero }}
            </td>
            <td>
                {{ reviewer.minus_one }}
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

symposion/templates/reviews/review_bulk_accept.html
{% extends "reviews/base.html" %}

{% load bootstrap_tags %}

{% block body %}
    <h1>Bulk Accept</h1>
    <form action="" method="POST" class="uniForm" accept-charset="utf-8">
        {% csrf_token %}
        {{ form|as_bootstrap }}
        <div class="form-actions">
            <input class="btn btn-primary" type="submit" name="submit" value="submit" />
        </div>
    </form>
{% endblock %}